fruit = '     Banana    '
find = fruit.find('n')
lower = fruit.lower()
upper = fruit.upper()
lstrip = fruit.lstrip()
rstrip = fruit.rstrip()
stripped = fruit.strip()
starting = fruit.startswith('B')
print (fruit)
print(find)
print(lower)
print(upper)
print(lstrip)
print(rstrip)
print(stripped)
print(starting)
